spring.application.name=trafficviolationdetectionandfinepotal

####################   server port #########################
server.port=8080
####################  Database Creds   ####################
spring.datasource.url=jdbc:mysql://localhost:3306/tvdfp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#################   NEW HIKARI CP Properties  ##########################
spring.datasource.hikari.max-lifetime=600000 
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=1000

#################    JSP CONFIG #######################################
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

server.error.whitelabel.enabled=false


spring.jpa.properties.hibernate.proc.param_null_passing=true

